### ISSUE TITLE
Difference from @google-cloud/secret-manager?

### ISSUE THREAD

**Issue by sethvargo** [alepacheco/gcp-secret-mananger#1]
Hi @alepacheco - could you help me understand the difference between this repo and https://www.npmjs.com/package/@google-cloud/secret-manager (https://github.com/googleapis/nodejs-secret-manager)?

**Comment by alepacheco** [comment]
This was made before any official library. You should use that one

**Comment by sethvargo** [comment]
Would you be willing to update the README to point to that instead? Some of our users are finding this library instead of the official ones and it's causing confusion. Thanks!
